nelmio_cors:
    defaults:
        allow_credentials: false
        allow_origin: ['http://localhost:3000', 'http://127.0.0.1:3000'] # adapte Ã  ton front, ou ['*'] en dev
        allow_headers: ['Content-Type', 'Accept', 'X-Requested-With', 'Authorization', 'X-AUTH-TOKEN']
        expose_headers: ['X-Debug-Token', 'X-Debug-Token-Link'] # utile pour debugger en dev
        allow_methods: ['GET', 'POST', 'PUT', 'DELETE', 'OPTIONS', 'PATCH']
        max_age: 3600
    paths:
        '^/api/':
            allow_origin: ['http://localhost:3000', 'http://127.0.0.1:3000']
            allow_headers: ['Content-Type', 'Accept', 'Authorization', 'X-AUTH-TOKEN']
            expose_headers: ['X-Debug-Token', 'X-Debug-Token-Link']
            allow_methods: ['GET', 'POST', 'PUT', 'DELETE', 'OPTIONS', 'PATCH']
            max_age: 3600