version: '3.8'
services:
  db_ecoride:
    image: mysql:8.0
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword_ecoride
      MYSQL_DATABASE: sf_EcoRide
      MYSQL_USER: kevin
      MYSQL_PASSWORD: kevin_password
    ports:
      - "3310:3306"
    volumes:
      - ecoride_db_data:/var/lib/mysql

  phpmyadmin_ecoride:
    image: phpmyadmin/phpmyadmin
    restart: unless-stopped
    depends_on:
      - db_ecoride
    environment:
      PMA_HOST: db_ecoride
    volumes:
      - ./phpmyadmin/config.user.inc.php:/etc/phpmyadmin/config.user.inc.php:ro
    ports:
      - "8082:80"

volumes:
  ecoride_db_data: